# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=kandan
quarkus.datasource.password=kandan
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kandan

# Hibernate
quarkus.hibernate-orm.validate-on-migration=false

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

# OpenAPI
mp.openapi.extensions.smallrye.info.title=Kandan API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API do sistema Kandan
